steps:
# Install
# - name: 'gcr.io/cloud-builders/yarn'
- name: $_NODE_VERSION
  entrypoint: $_PACKAGE_MANAGER
  args: []
# Lint
- name: $_NODE_VERSION
  entrypoint: $_PACKAGE_MANAGER
  args: ['lint']
# Test
# - name: $_NODE_VERSION
# entrypoint: $_PACKAGE_MANAGER
#   args: ['test']
# Build
- name: $_NODE_VERSION
  entrypoint: $_PACKAGE_MANAGER
  args: ['build', '--prod']
# Deploy
- name: $_NODE_VERSION
  entrypoint: $_PACKAGE_MANAGER
  args: ['firebase', 'deploy']
substitutions:
  _NODE_VERSION: node:10.15.3
  _PACKAGE_MANAGER: yarn
